### ISSUE TITLE
Unable to build a sample app using yeoman

### ISSUE THREAD

**Issue by irisli** [stellar/generator-interstellar#1]
Reported by [johnicholas in Stellar Public Slack](https://stellar-public.slack.com/archives/general/p1434726504001340). Below is my attempt on my own machine.

```bash
irisli@Iriss:~/yotest  npm install -g yo generator-interstellar
irisli@Iriss:~/yotest  yo interstellar sample-app
  Error interstellar sample-app

  You don't seem to have a generator with the name interstellar installed.
  You can see available generators with npm search yeoman-generator and then install them with npm install [name].
  To see the 0 registered generators run yo with the `--help` option.
```

What is happening here?

**Comment by bartekn** [comment]
Do any of [these tips](https://github.com/yeoman/yeoman/issues/1297) solve this problem for you?

**Comment by irisli** [comment]
It says that my npm and node.js version is outdated. Which is a given since we're using legacy node.

But I thought you use v0.10.33 too?

**Comment by bartekn** [comment]
[Trying](https://stellar-public.slack.com/archives/dev/p1435169917000652) to solve a problem with johnnicholas on Slack.
